version: "3.7"
services:
  kibana_test:
    container_name: kibana_test
    image: docker.elastic.co/kibana/kibana:7.7.0
    restart: always
    depends_on:
      - elasticsearch_test
    environment:
      ELASTICSEARCH_URL: http://elasticsearch_test:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch_test:9200
    ports:
      - "5601:5601"
    networks:
      - esnet
  elasticsearch_test:
    container_name: elasticsearch_test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge
