/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mac_controller.h)                                          */
/* BINDTOOL_HEADER_FILE_HASH(a96a21a3d165e6bd627f48e6857ffa67)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <tacmac/mac_controller.h>
// pydoc.h is automatically generated in the build directory
#include <mac_controller_pydoc.h>

void bind_mac_controller(py::module& m)
{

    using mac_controller = ::gr::tacmac::mac_controller;


    py::class_<mac_controller,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<mac_controller>>(m, "mac_controller", D(mac_controller))

        .def(py::init(&mac_controller::make),
             py::arg("destination_id"),
             py::arg("source_id"),
             py::arg("mtu_size"),
             D(mac_controller, make))

        .def("replay_mode", &mac_controller::replay_mode)
        .def("activate_replay_mode",
             &mac_controller::activate_replay_mode //,
                                                   //    py::arg("activate") //,
             //    D(mac_controller, activate_replay_mode)
        )

        ;
}
