/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(periodic_time_tag_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a2ce84a58afffa4efe6b2fb170b9c29a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <tacmac/periodic_time_tag_cc.h>
// pydoc.h is automatically generated in the build directory
#include <periodic_time_tag_cc_pydoc.h>

void bind_periodic_time_tag_cc(py::module& m)
{

    using periodic_time_tag_cc = ::gr::tacmac::periodic_time_tag_cc;


    py::class_<periodic_time_tag_cc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<periodic_time_tag_cc>>(
        m, "periodic_time_tag_cc", D(periodic_time_tag_cc))

        .def(py::init(&periodic_time_tag_cc::make),
             py::arg("samp_rate"),
             py::arg("tag_interval"),
             D(periodic_time_tag_cc, make))


        ;
}
