name: Check Formatting

on:
  push:
    paths-ignore:
      - './python/bindings/docstrings/'
  pull_request:
    paths-ignore:
      - './python/bindings/docstrings/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gnuradio/clang-format-lint-action@v0.5-4
      with:
        source: '.'
        exclude: './python/bindings/docstrings/'
        extensions: 'c,cc,cpp,cxx,h,hh'
